// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxnCLvwYvdDlMr3yAEfB3u2RKklcWAGpQ',
    appId: '1:758901123463:web:fb96832d44bb97001acb22',
    messagingSenderId: '758901123463',
    projectId: 'barter-3bd92',
    authDomain: 'barter-3bd92.firebaseapp.com',
    storageBucket: 'barter-3bd92.appspot.com',
    measurementId: 'G-8YGD98PT7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-bb9eArgEvoZpTIMvuDcz7RQswg7F4dU',
    appId: '1:758901123463:android:09c3a75f23b534871acb22',
    messagingSenderId: '758901123463',
    projectId: 'barter-3bd92',
    storageBucket: 'barter-3bd92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlpIEitygS3I5grixGfPyhKK6LepZ9tq8',
    appId: '1:758901123463:ios:54749803f2adc2511acb22',
    messagingSenderId: '758901123463',
    projectId: 'barter-3bd92',
    storageBucket: 'barter-3bd92.appspot.com',
    iosBundleId: 'com.example.barterProject2023',
  );
}
