// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ2KLT3mT2pRCDlbrzUi3lqvNGc2DvtJ4',
    appId: '1:415432673614:web:2273ff47f3e2dde218b61f',
    messagingSenderId: '415432673614',
    projectId: 'barter-4521d',
    authDomain: 'barter-4521d.firebaseapp.com',
    storageBucket: 'barter-4521d.appspot.com',
    measurementId: 'G-3FVX75D36Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLdYf6USowjDKRI5DQK7p-geP3kfZgH34',
    appId: '1:415432673614:android:ce5b8379baba0df718b61f',
    messagingSenderId: '415432673614',
    projectId: 'barter-4521d',
    storageBucket: 'barter-4521d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsEYZuKzX0JfF4ooSIgZnx77zeqEZ4ueo',
    appId: '1:415432673614:ios:a801a8a69aa9191218b61f',
    messagingSenderId: '415432673614',
    projectId: 'barter-4521d',
    storageBucket: 'barter-4521d.appspot.com',
    iosBundleId: 'com.example.barterProject2023',
  );
}
